name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: test-report.html

      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
