name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests and generate HTML report
        run: |
          # Add your test commands here
          # For example, if you're using a specific testing framework:
          # npm install
          # npm test

          # Generate HTML report (replace with your actual command)
          echo '<html><body><h1>Test Report</h1><p>Test results go here.</p></body></html>' > test-report.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: test-report.html

      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
