name: Venkatesh_4_24

on:
  push:
    branches: ["Venkatesh_04_24"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run PostManCollection/mycollection1.postman_collection.json --reporters cli,html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: postman-html-report
          path: newman/*.html
